# Default versions of tools, to update these, set [tools.override]
[tools]
dprint = "latest"
golang = "1.26.3"
golangci-lint = "2.11.4"
goreleaser = "latest"
gotestsum = "1.13.0"
"go:golang.org/x/tools/cmd/goimports" = "latest"
shfmt = "latest"

[tasks.build]
description = "Build a binary for the current platform/architecture"
run = "go build -trimpath -o ./bin/ -v ./cmd/..."

[tasks.fmt]
alias = "format"
description = "Format code"
run = ["go mod tidy", "gofmt -s -w .", "goimports -w .", "shfmt -w ."]

[tasks.lint]
description = "Run linters"
run = "golangci-lint run"

[tasks.test]
description = "Run tests"
run = "gotestsum"

## <<Stencil::Block(custom)>>
[tasks.ci-local]
run = [
	"act --platform ubuntu-latest=ghcr.io/catthehacker/ubuntu:gh-24.04 --job test-action --secret GITHUB_TOKEN=$(gh auth token)",
]
## <</Stencil::Block>>
