name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      # TODO(jaredallard): Support local builds.
      - name: Use known good version
        run: |-
          echo "action_ref=v0.2.0" >> shim/shim-config.yml

      - uses: ./
        env:
          GH_TOKEN: ${{ github.token }}
