name: release

on:
  # Only run when triggered through the Github UI or API.
  workflow_dispatch:
    inputs:
      version:
        description: "Set a specific version to release"
        required: true
        type: string

permissions:
  contents: write
  packages: write
  issues: write
  # Used by attestations in the release workflow.
  id-token: write
  attestations: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: jdx/mise-action@v3
        with:
          experimental: true
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Get Go directories
        id: go
        run: |
          echo "cache_dir=$(go env GOCACHE)" >> "$GITHUB_OUTPUT"
          echo "mod_cache_dir=$(go env GOMODCACHE)" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v5
        with:
          path: ${{ steps.go.outputs.cache_dir }}
          key: ${{ github.workflow }}-${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}
      - uses: actions/cache@v5
        with:
          path: ${{ steps.go.outputs.mod_cache_dir }}
          key: ${{ github.workflow }}-${{ runner.os }}-go-mod-cache-${{ hashFiles('go.sum') }}
      - name: Retrieve goreleaser version
        run: |-
          echo "version=$(mise current goreleaser)" >> "$GITHUB_OUTPUT"
        id: goreleaser
      - name: Set up git user
        uses: fregante/setup-git-user@v2
      - name: Download syft (SBOM)
        uses: anchore/sbom-action/download-syft@v0

      - name: Create Tag
        env:
          NEXT_VERSION: ${{ inputs.version }}
        run: |-
          git tag -a "$NEXT_VERSION" -m "Release $NEXT_VERSION"
      - name: Create release artifacts and Github Release
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: v${{ steps.goreleaser.outputs.version }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/attest-build-provenance@v3
        with:
          # We attest all generated _archives_ because those are what we
          # upload to Github Releases.
          subject-path: dist/stencil-action_*.*, dist/checksums.txt
